# Welcome to Jekyll!
#

# Site settings
title: ilias zavitsanos
description: |
  PhD, Computer Science
  crafted by [HTML5 UP](http://html5up.net)
owner: izavits
first_published: 2019 # if migrating another site, the year of your first publish
email: izavits@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "izavits.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/izavits
  github: https://github.com/izavits
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/izavits
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:izavits@gmail.com
  flickr: https://www.flickr.com/photos/izavits/
  instagram: https://www.instagram.com/izavits/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
